### ISSUE TITLE
Missing X509 certificate on system will cause "Invalid InterceptionId" error

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#192] opened 2020-08-24 07:31 UTC
I was going to implement file download
```
    wait := p.GetDownloadFile("data:*")
    p.Search(`/html/body/div[8]/div/div/div[3]/div/div/button[1]`).Click()  //Stuck when running this step
    res := wait()
```
Then I wrote like this:
```
        ch := make(chan []byte)
        router := p.HijackRequests()
        router.Add(`*`, func(ctx *rod.Hijack) {
		rod.Try(func() {
			ctx.LoadResponse()
			ch <- ctx.Response.Body()
		})
	})
	go router.Run()
        defer router.Stop()
        p.Search(`/html/body/div[8]/div/div/div[3]/div/div/button[1]`).Click()

        select {
	case val := <-ch:
		
	case <-time.After(5 * time.Second):
		fmt.Println("timeout!")
	}

```
It runs normally on windows, but it runs wrong on linux
error message:
[rod hijack err] {"code":-32602,"message":"Invalid InterceptionId.","data":""}

Any suggestions, thanks

**Comment by ysmood** [comment] 2020-08-24 15:28
feels like an duplicate of https://github.com/go-rod/rod/issues/174

have you checked the above one?

**Comment by Abin01** [comment] 2020-08-25 02:56
The above questions have been checked.
Sorry, the detailed code cannot be provided at the moment, I am trying another method

**Comment by Abin01** [comment] 2020-08-26 01:05
The problem is solved. On linux, because of the X509 certificate error, the code runs normally after adding the other party's certificate to the trust.
Thanks

**Comment by ysmood** [comment] 2020-08-26 01:38
Glad you solved it, I will close it for now.

**Closed by ysmood** 2020-08-26 01:38 UTC
Labels: question
