### ISSUE TITLE
Create docker image builds for linux/arm and linux/arm64

### ISSUE THREAD

**Issue by mathijshoogland** [go-rod/rod#268] opened 2020-11-07 08:32 UTC
## Is your feature request related to a problem
The go-rod/rod image provided in the docker image repository is built for the x86 architecuture. With the rise of arm architecture on smaller portable devices (i.e. raspberry pi) it makes sense to also create a arm based image.

## Describe the solution you'd like
Add images for arm.

**Comment by ysmood** [comment] 2020-11-07 09:11
Agree. Can you help us to investigate how to do it?

**Comment by mathijshoogland** [comment] 2020-11-07 09:59
Sure! I actually built an rodorg/rod image locally for arm64 currently running on my raspberry pi by using buildx. How are images now distrubted to dockerhub? If you give me access I could see if I can modify the pipeline (here some info on how it can be done: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ )

**Comment by ysmood** [comment] 2020-11-07 10:03
Great. Everything in Rod is public, it's the same with the docker image. Once your dockerfile is merged, it will automatically be available in dockerhub. The current image is built by this: https://github.com/go-rod/rod/tree/master/lib/docker

The github CI will check the dockerfile with all the unit tests. Feel free to play with it.

**Comment by ysmood** [comment] 2020-11-07 10:20
The plan is simple, you will add new dockerfiles like `arm.Dockerfile` and `arm64.Dockerfile` to the folder, I will add new build rules here to auto-build it:

![image](https://user-images.githubusercontent.com/1415488/98438521-349f4f00-212e-11eb-8148-be5a9b7494aa.png)

**Comment by mathijshoogland** [comment] 2020-11-07 10:25
Afaik no changes are needed, so you can simply use the same dockerfile.

**Comment by ysmood** [comment] 2020-11-07 10:27
Then that's even better. Feel free to change any file you like.

BTW, how do we test it? I don't have an arm machine on hand.

**Comment by ysmood** [comment] 2020-11-10 19:16
Some useful links: https://github.com/docker/for-mac/issues/4733

**Comment by lox** [comment] 2021-03-01 23:25
I have an M1 MacBook Air if I can be of help with testing @ysmood!

**Comment by lox** [comment] 2021-03-01 23:30
On the latest master (ad95d98dc1d87f955e1a0e10121b294a2349dfd4) I built with the following:

```
$ uname -a 
Darwin Alexandra 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

$ docker build -t rodorg/rod -f lib/docker/Dockerfile .
...
 => => exporting layers                                                                                                                                                                                 3.4s
 => => writing image sha256:61bbd09dce07cb7c060d467cef1962a19ec1ccf09af6591410e4aec91c46e6e7                                                                                                            0.1s
 => => naming to docker.io/rodorg/rod

$ docker run -p 9222:9222 docker.io/rodorg/rod
Remote control url is ws://[::]:9222
2021/03/01 23:27:45 http: panic serving 172.17.0.1:55734: [launcher] Failed to get the debug url: qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

goroutine 34 [running]:
net/http.(*conn).serve.func1(0x4000188000)
	/usr/local/go/src/net/http/server.go:1824 +0x110
panic(0x2c52c0, 0x4000212000)
	/usr/local/go/src/runtime/panic.go:971 +0x424
github.com/go-rod/rod/lib/utils.E(...)
	/rod/lib/utils/utils.go:67
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0x4000182100, 0x0, 0x0)
	/rod/lib/launcher/launcher.go:319 +0xb0
github.com/go-rod/rod/lib/launcher.(*RemoteLauncher).launch(0x4000098ef0, 0x392d20, 0x40001ae000, 0x400019e000)
	/rod/lib/launcher/remote_launcher.go:118 +0x148
github.com/go-rod/rod/lib/launcher.(*RemoteLauncher).ServeHTTP(0x4000098ef0, 0x392d20, 0x40001ae000, 0x400019e000)
	/rod/lib/launcher/remote_launcher.go:97 +0xcc
net/http.serverHandler.ServeHTTP(0x400011a000, 0x392d20, 0x40001ae000, 0x400019e000)
	/usr/local/go/src/net/http/server.go:2887 +0xbc
net/http.(*conn).serve(0x4000188000, 0x3933a0, 0x4000196000)
	/usr/local/go/src/net/http/server.go:1952 +0x71c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x318
```

🤔

**Comment by ysmood** [comment] 2021-03-02 02:28
@lox Thanks for your info.

I think you should use the image you build. Can you try this:

```bash
docker build -t rodorg/rod -f lib/docker/Dockerfile .
docker run -p 9222:9222 rodorg/rod
```

**Comment by lox** [comment] 2021-03-02 03:12
I thought it was odd that the builder didn't use the tag I specified, but I must have been misreading the output of `buildx`.

The command as you mentioned above works as expected!

**Comment by ARolek** [comment] 2022-09-09 20:32
@ysmood I'm also interested in this. I did a bunch of testing on my M1 Mac and here are my findings:

1. Building the go-rod `Dockerfile` locally is necessary, but I was not able to successfully run the container using the base image `ubuntu:bionic`.  I had to upgrade the `ubuntu:focal`. When using `ubuntu:bionic` I would get a GLIB version error. 
2. The architecture support needed for Apple silicon is `linux/arm64/v8`

It looks like the GH Container registry supports [multi architecture builds](https://github.blog/changelog/2020-09-17-github-container-registry-support-for-multi-arch-images/)

* Would you accept a PR that upgrades the base image of the DockerFile to `ubuntu:focal`? 
* Would you accept a PR to enhance your CI to include multi arch building of the docker container and pushing it to the GH Container Registry?

**Comment by ysmood** [comment] 2022-09-09 23:32
@ARolek Sure thing！

**Comment by SantoshSah** [comment] 2022-09-21 14:44
@ysmood I am able to build docker image for `linux/arm64` on M1 Macbook by installing chrome dependencies in base image(golang). Thank you @ARolek for fixing this issue.

**Comment by ysmood** [comment] 2022-09-21 15:10
I'm still working on it, works fine on my local machine, but github actions doesn't work, I still don't know why.

**Comment by ysmood** [comment] 2022-09-21 15:50
@ARolek No, because I want developers to use images that are cross built under trustable third party machines, not mine. I don't have enough donation to buy third party macos vps.

**Comment by SantoshSah** [comment] 2022-09-21 16:03
> I'm still working on it, works fine on my local machine, but github actions doesn't work, I still don't know why.

For which platforms you are building on local machine? Which machine you are using as local? For me, it builds for `linux/arm64` but not for `linux/amd64` on M1 Macbook.

**Comment by ARolek** [comment] 2022-09-21 16:05
I think you can still use the GH macos runner and then push the arch specific build to the GH container registry. GitHub has this runner available as a default option with the included free tier for open source projects. It does use minutes faster than Ubuntu, but I have never had an issue I bing out of build time on other open source projects.

**Comment by SantoshSah** [comment] 2022-09-21 17:24
> > I'm still working on it, works fine on my local machine, but github actions doesn't work, I still don't know why.
> 
> For which platforms you are building on local machine? Which machine you are using as local? For me, it builds for `linux/arm64` but not for `linux/amd64` on M1 Macbook.

Update: After pulling your latest changes, i can successfully build docker images for `linux/arm64` and `linux/amd64` in local(M1 Macbook) and using github action. I have forked and added another github actions for multi-arch build.

**Comment by ysmood** [comment] 2022-09-22 01:53
The problem is I want to test the docker image before releasing it, or it will make PR able to release docker images to the rod official registry.

**Comment by ysmood** [comment] 2022-09-22 01:57
@ARolek GH macos doesn't support docker, I already tried it.

**Comment by SantoshSah** [comment] 2022-09-22 10:55
@ysmood GH macos does not natively support docker but we can install docker using [colima](https://github.com/abiosoft/colima) and build images. I have added a [GH action for multi-arch build using macos-12 runner](https://github.com/SantoshSah/rod/blob/master/.github/workflows/on_push_master_macos.yml). It works but more than 3 times slower than Ubuntu runner.

**Comment by ysmood** [comment] 2022-09-23 09:02
I think we can close this issue now, I have fixed the CI, just added some todo for Github Actions bugs.

On Apple silicon machines you can just pull without any tag, it will automatically choose the right image for you: `docker pull ghcr.io/go-rod/rod`

Now rod images use docker manifest to support multi-arch, for example:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1415488/191926732-ead91cae-eb5f-44c0-ba45-63f52505e656.png">

**Closed by ysmood** 2022-09-23 09:02 UTC
Labels: enhance
